language: rust
os:
- linux
- osx
rust:
- stable
script: |
  set -e

  release=0
  target=
  version=

  tag="$(git name-rev --name-only HEAD)"

  if [[ "$tag" == tags/v* ]]; then
    release=1
    version="$(sed 's/^tags\/v//' <<< $tag)"
  fi

  if [ "$release" = 1 ]; then
    if [ "$TRAVIS_OS_NAME" = 'linux' ]; then
      rustup target add x86_64-unknown-linux-musl
      target='--target x86_64-unknown-linux-musl'
    fi

    sed "s/^version = \"0.0.1\"$/version = \"$version\"/" Cargo.toml > Cargo.toml.new
    mv Cargo.toml.new Cargo.toml
    cat Cargo.toml
    git add -A
    git commit -m "version $version"
  fi

  rustup component add rustfmt-preview
  cargo fmt && git diff --quiet
  cargo build $target --release
  cargo test $target --release

  mkdir target/upload

  if [ "$release" = 1 ]; then
    if [ "$TRAVIS_OS_NAME" = 'linux' ]; then
      cp target/x86_64-unknown-linux-musl/release/fsw target/upload/fsw-linux-amd64
    elif [ "$TRAVIS_OS_NAME" = 'osx' ]; then
      cp target/release/fsw target/upload/fsw-darwin-amd64
    elif [ "$TRAVIS_OS_NAME" = 'windows' ]; then
      cp target/release/fsw.exe target/upload/fsw-windows.exe
    fi

    if [ "$CRATES_API_KEY" != '' ] && [ "$TRAVIS_OS_NAME" = 'linux' ]; then
      cargo login "$CRATES_API_KEY"
      cargo publish
    fi
  fi

env:
  global:
    secure: "Ub9/Xb6UR51Z6YM+uo5PycOW6P+gkm6q+X1VOQKFugAHba0Dp92GY9jqLz9oPj7vG7nakURdH+FsmK3M6t/LNHFhEcvXjCnhunti173IP4FD7QlbVtIlCSS5YqS65/18vKYN7ewXLPJapFcCE29f7lqbtfV/D+9zgS5WVj8FsciIcmsh+IbF9dBLemGWU55RDhh32g4yeTHoZq/ygcNlzxOWN+cJmV+3PMMU8OI/BRwkBWAyMSWTOuYQdMdcDpgR/Rc+Z5k87wDn36P0JlF2mtof6yDvg5wpgx56w4JLtD1iDd0ZYThhHa7WJ0uhFgXFg6+C9k2ALuOcBJ3rOQ5Wujo9y70EW20wpJ5V0YNQOmdHz0a8kUNLI5YhGlzza/FQZc11+IaF38JoeOD26ycwHwAfChDR+lfwHQuc2hBw9wqEtysLkqC/qBAMx0mDujmYwOcn6YyQZ+j4t1f4Z7UmxvlUA1vof5x4cEZNQRWHw9YOImGv8J75VCkfGTa0625t3TNGUjC0sD+Stkyywjd6AuPu1g2LvTm2X7Zgv3irG8nc4ZJ5Gg0j/uN43W7Mw7vXehn1nbSy8eCP1D33lExxqdtNtQjvHmbyic4qwrR6jcv/senqtseazUH6vpD6rh2FU2lsVqPvWMmR4aPgREH/m5r0W0wKFwDcsxIsih9+P1I="

deploy:
  provider: releases
  api_key:
    secure: vANVoUd86OPJMCZMDuk5qX+RXZ429/rT8auvrfoA7f9LrS6vP9nqpLe3kFOc/BbXl/7V+oJBeCvAWbXydo/raOgzYSA1Vk/RMEcuFosoVxqlMvTbEkvzVDmZLF+q8w3sZ5MNNXf2jaboFi47Kff2Y02+ezPr1K9aZyziIK5oBBVESapewdnSz+6iqlVk5t6D1pelBejdjt9jKcqDkycYgPF2qmom4InPmrABxLRbgxLkuksSkRJFr/XgSVHU5ufb3OI42ATKD9pVNIX4cEgUgXM5AWYHbYXNDMNntEWzWrfGefEdpWoCKAw1rZWo9ZYZMxOKhwCEy2NSGQgdK2ReVqwsA8+6k/WY5r96A7ANSVlDGpfHmr3SxNPQdvY9DIzmHnJ7Rq4MQtBKV3f/DjJS9IKpc/YqdObdrLAIldN6CsK6S/d4lh6Eo9hivUcUMPvWYKGGe2cmBiKZVbbkjRRfgKIzRMHSuI1sn9CbJi3iKDsZIhAn1k1TrhorfsvYr4NHdEwgEaV+ysJvhNOh7ql5P2BeRagEXxMcRsLP6K3XhzLEqPuxb4XzWkJrpv7LgwEj8iIax+nzufoY4l7+mceBb6IaIFmHt8GEIpKylk37wZCPlcMa5KnsXbYT7vFhUD/cZsLASnIaaO9oELIZ17XIfdBXJaFMu6I996nULPO43p8=
  skip_cleanup: true
  file_glob: true
  file: target/upload/*
  on:
    tags: true
